<?php

$plans = static function (
    string $environmentPrefix,
    string $entitlementPrefix,
    array $freeFeatures,
    array $paidFeatures,
): array {
    return [
        'free' => [
            'name' => 'Free',
            'price' => '0.00',
            'currency' => env("BUSINESS_{$environmentPrefix}_PAID_CURRENCY", 'USD'),
            'billing_period' => null,
            'stripe_price_id' => null,
            'stripe_required' => false,
            'entitlement' => "{$entitlementPrefix}.free",
            'features' => $freeFeatures,
        ],
        'paid' => [
            'name' => 'Paid',
            'price' => env("BUSINESS_{$environmentPrefix}_PAID_PRICE"),
            'currency' => env("BUSINESS_{$environmentPrefix}_PAID_CURRENCY", 'USD'),
            'billing_period' => env("BUSINESS_{$environmentPrefix}_PAID_BILLING_PERIOD", 'month'),
            'stripe_price_id' => env("STRIPE_{$environmentPrefix}_PAID_PRICE_ID"),
            'stripe_required' => true,
            'entitlement' => "{$entitlementPrefix}.access",
            'features' => $paidFeatures,
        ],
    ];
};

$product = static function (
    string $name,
    string $summary,
    string $description,
    string $freeDelivery,
    string $paidDelivery,
    array $documentation,
    array $plans,
): array {
    return [
        'name' => $name,
        'availability' => 'In development',
        'summary' => $summary,
        'description' => $description,
        'delivery' => "The free tier {$freeDelivery} The paid tier {$paidDelivery}",
        'documentation' => [
            'status' => 'Free and paid tiers in development',
            ...$documentation,
        ],
        'plans' => $plans,
    ];
};

return [
    'accounts-client' => $product(
        'Accounts Client',
        'Provider-independent login and Accounts API integration for Laravel products.',
        'Accounts Client coordinates external login, stable Accounts identities, and entitlement decisions without sharing the Accounts database.',
        'is delivered as a Composer package.',
        'is planned as managed Accounts connectivity and operational support.',
        [
            'purpose' => 'Connect products to central identity and entitlement decisions without duplicating provider-specific security code.',
            'audiences' => ['Laravel product teams', 'Developers integrating Accounts', 'Operators maintaining product access'],
            'inputs' => ['A verified external identity', 'Accounts service credentials', 'A named entitlement request'],
            'workflow' => [
                ['name' => 'Initiate login', 'description' => 'The application delegates authentication to its configured external identity driver.'],
                ['name' => 'Resolve account', 'description' => 'The verified identity resolves to one stable Accounts account.'],
                ['name' => 'Request entitlement', 'description' => 'The product asks Accounts for a provider-independent access decision.'],
                ['name' => 'Project locally', 'description' => 'The product keeps only its local session and product-specific account projection.'],
            ],
            'outputs' => ['Stable account references', 'Typed entitlement decisions', 'Provider-independent response values'],
            'interactions' => ['Install the package', 'Configure a login driver', 'Call authenticated Accounts endpoints', 'Handle allowed and denied decisions'],
            'integrations' => ['Laravel', 'Accounts', 'External identity providers', 'Connected product applications'],
            'data_boundaries' => ['Identity providers own credentials and authentication sessions.', 'Accounts owns stable identities and entitlements.', 'Product applications own local sessions and product state.', 'Accounts Client stores neither credentials nor shared account records.'],
            'limits' => ['The production identity provider and service-authentication protocol are not selected.', 'The paid managed service is not available yet.', 'NativePHP integration follows the browser MVP.'],
        ],
        $plans('ACCOUNTS_CLIENT', 'accounts-client',
            ['Composer package and public contracts', 'Provider-independent login driver contract', 'Typed account and entitlement response values'],
            ['Managed Accounts API connectivity', 'Hosted login coordination and entitlement access', 'Operational monitoring and integration support'],
        ),
    ),
    'aleph' => $product(
        'Aleph',
        'Bounded, provenance-preserving ingestion from external sources.',
        'Aleph runs resumable, policy-bounded ingestion jobs and submits retrieved observations and discovery provenance to Funes.',
        'is delivered as a Laravel package.',
        'is planned as hosted ingestion, scheduling, and managed operations.',
        [
            'purpose' => 'Collect external material predictably while preserving what was attempted, retrieved, skipped, and discovered.',
            'audiences' => ['Developers building ingestion pipelines', 'Researchers collecting public sources', 'Operators supervising recurring imports'],
            'inputs' => ['Configured sources and seeds', 'Host and exclusion policy', 'Page, depth, timeout, and response-size limits'],
            'workflow' => [
                ['name' => 'Declare source', 'description' => 'A source defines seeds, permitted hosts, exclusions, signals, and traversal limits.'],
                ['name' => 'Run ingestion', 'description' => 'Aleph retrieves permitted resources through a bounded, resumable frontier.'],
                ['name' => 'Extract mechanically', 'description' => 'Versioned extractors preserve text and typed discoveries without interpreting them.'],
                ['name' => 'Persist evidence', 'description' => 'Funes accepts observations and provenance before work is marked complete.'],
            ],
            'outputs' => ['Resumable ingestion state', 'Retrieved observations and extraction results', 'Deterministic inventory exports', 'Discovery and skip provenance'],
            'interactions' => ['Configure a source', 'Start or resume a crawl', 'Inspect run status', 'Export JSON or CSV inventory'],
            'integrations' => ['Laravel', 'Funes', 'Public HTTP sources', 'PDF text extraction'],
            'data_boundaries' => ['Aleph owns ingestion attempts and frontier state.', 'Funes owns accepted observations and extraction history.', 'Source systems remain authoritative.', 'Consumers interpret evidence outside Aleph.'],
            'limits' => ['Current crawling is sequential and public-web only.', 'Scripts, forms, OCR, and semantic interpretation are outside the current package.', 'Hosted scheduling is not available yet.'],
        ],
        $plans('ALEPH', 'aleph',
            ['Laravel ingestion package', 'Bounded public-web crawling', 'Resumable runs and deterministic inventory exports'],
            ['Hosted and scheduled ingestion runs', 'Managed storage, monitoring, and larger crawl allowances', 'Operational support and retained run history'],
        ),
    ),
    'bindle' => $product(
        'Bindle',
        'A visual component workbench for AI-assisted design, assets, testing, and screenshots.',
        'Bindle is the planned inspection and testing surface for visual components and generated assets, including specimens, screenshots, comparisons, and later document rendering checks.',
        'is planned as a local Laravel package and workbench.',
        'is planned as hosted visual testing, retained review history, and collaboration.',
        [
            'purpose' => 'Make AI-assisted interface and asset work observable, repeatable, and reviewable through rendered specimens and visual evidence.',
            'audiences' => ['Design-system maintainers', 'Developers building visual components', 'Teams reviewing AI-generated design and assets'],
            'inputs' => ['Components or visual assets', 'Named states and viewport sizes', 'Reference images or approved baselines', 'Optional PDF, print, or OCR scenarios'],
            'workflow' => [
                ['name' => 'Register specimen', 'description' => 'A component or asset is presented in explicit variants, states, and content conditions.'],
                ['name' => 'Render target', 'description' => 'Bindle renders the specimen at selected viewports or document formats.'],
                ['name' => 'Capture evidence', 'description' => 'Screenshots and relevant metadata are recorded for inspection.'],
                ['name' => 'Review change', 'description' => 'A person or agent compares the result with expectations and records an outcome.'],
            ],
            'outputs' => ['Interactive component specimens', 'Repeatable screenshots', 'Visual comparison results', 'Reviewable asset and rendering evidence'],
            'interactions' => ['Browse components', 'Select states and viewports', 'Capture screenshots', 'Compare a baseline', 'Approve or reject changes'],
            'integrations' => ['Official Burd Design', 'Browser screenshot tools', 'AI design and asset generators', 'Future PDF, OCR, and print workflows'],
            'data_boundaries' => ['Design systems own production components and tokens.', 'Bindle owns specimens, capture configuration, and visual-test evidence.', 'Source assets remain in their repositories.', 'Approvals remain human decisions.'],
            'limits' => ['The current package is an early scaffold.', 'Browser, baseline, PDF, OCR, and print contracts remain to be implemented.', 'Hosted review is not available yet.'],
        ],
        $plans('BINDLE', 'bindle',
            ['Local component and asset workbench', 'Interactive specimens and manual screenshot capture', 'Local visual comparison workflows'],
            ['Hosted screenshot and visual-regression runs', 'Retained baselines, review history, and collaboration', 'Higher-volume rendering plus PDF, OCR, and print workflows'],
        ),
    ),
    'burdgeon' => $product(
        'Burdgeon',
        'An evidence-backed project workspace for understanding history and supervising agent work.',
        'Burdgeon brings project history, current state, active work, decisions, and supporting evidence into one desktop and mobile workspace.',
        'is planned as a personal project workspace.',
        'is planned as hosted synchronization, background supervision, and collaboration.',
        [
            'purpose' => 'Help people resume projects, understand why work changed, and supervise agent activity from one project-centered interface.',
            'audiences' => ['People working across long-running projects', 'Teams collaborating with agents', 'Operators supervising background work'],
            'inputs' => ['Project history and evidence', 'Conversations, tasks, commits, files, and agent runs', 'Questions and requested actions'],
            'workflow' => [
                ['name' => 'Open project', 'description' => 'The workspace presents current state, recent activity, and work needing attention.'],
                ['name' => 'Inspect evidence', 'description' => 'History remains connected to canonical conversations, files, runs, and decisions.'],
                ['name' => 'Ask or act', 'description' => 'The user asks a question or starts, redirects, pauses, or resumes work.'],
                ['name' => 'Review outcome', 'description' => 'Cited answers, execution results, failures, and approval requests return to the project view.'],
            ],
            'outputs' => ['Evidence-backed project briefings', 'Navigable timelines', 'Agent-run status and artifacts', 'Explicit questions and approvals'],
            'interactions' => ['Resume a project', 'Follow citations', 'Ask what changed', 'Supervise background work', 'Review agent requests'],
            'integrations' => ['Funes history', 'Menard retrieval', 'Kilgore interpretation', 'Logres execution'],
            'data_boundaries' => ['Burdgeon owns the project workspace.', 'Funes preserves evidence.', 'Menard prepares context.', 'Kilgore produces interpretations.', 'Logres owns executable work.'],
            'limits' => ['The first evidence-backed project workflow is still being built.', 'Team collaboration and hosted synchronization are not available yet.', 'Provider coverage depends on ingestion adapters.'],
        ],
        $plans('BURDGEON', 'burdgeon',
            ['Personal project workspace', 'Local history inspection and cited answers', 'Manual review of agent work and artifacts'],
            ['Hosted project synchronization and background supervision', 'Shared projects, collaboration, and retained activity', 'Managed integrations, notifications, and support'],
        ),
    ),
    'funes' => $product(
        'Funes',
        'A provenance-first historical record substrate for applications and agents.',
        'Funes preserves immutable observations, source identity, timing, relationships, extraction history, and repeated-ingestion semantics.',
        'is delivered as a Laravel package.',
        'is planned as hosted historical storage, ingestion, and managed retrieval infrastructure.',
        [
            'purpose' => 'Preserve selected history without losing its source, sequence, identity, or relationship to later interpretations.',
            'audiences' => ['Laravel developers', 'Teams building application memory', 'Agent and automation platform builders'],
            'inputs' => ['Source and resource references', 'Observation time and raw payload', 'Metadata and typed discoveries', 'Versioned extraction results'],
            'workflow' => [
                ['name' => 'Describe observation', 'description' => 'A caller supplies source identity, resource identity, timing, payload, and provenance.'],
                ['name' => 'Accept idempotently', 'description' => 'Funes records a first, unchanged, or changed observation without duplicating effects.'],
                ['name' => 'Relate evidence', 'description' => 'Discoveries and extraction results remain connected to their observation.'],
                ['name' => 'Retrieve history', 'description' => 'Consumers recover immutable evidence and citations for later use.'],
            ],
            'outputs' => ['Immutable accepted observations', 'First, unchanged, or changed dispositions', 'Discovery and extraction provenance', 'Stable evidence references'],
            'interactions' => ['Submit an observation', 'Retrieve historical evidence', 'Record an extraction', 'Traverse discovery provenance'],
            'integrations' => ['Laravel database storage', 'Aleph ingestion', 'Menard retrieval', 'Kilgore interpretation'],
            'data_boundaries' => ['Funes owns accepted observations and provenance.', 'Sources remain authoritative.', 'Indexes and interpretations are replaceable projections.', 'Consumers decide source-specific identity.'],
            'limits' => ['The current slice focuses on database-backed observations and extractions.', 'Hosted storage and managed search are not available yet.', 'Funes preserves evidence but does not interpret it.'],
        ],
        $plans('FUNES', 'funes',
            ['Laravel observation-store package', 'Idempotent immutable history and provenance', 'Versioned extraction and discovery records'],
            ['Hosted historical storage and managed ingestion', 'Retention, backup, monitoring, and scalable retrieval', 'Managed connectors and operational support'],
        ),
    ),
    'kilgore' => $product(
        'Kilgore',
        'Evidence-backed interpretation of project history.',
        'Kilgore turns commits, tasks, conversations, decisions, commands, documents, and agent runs into cited answers, timelines, and briefings.',
        'is planned as a Laravel interpretation package.',
        'is planned as hosted model-backed analysis, recurring briefings, and monitoring.',
        [
            'purpose' => 'Explain what happened while keeping facts, inference, uncertainty, and supporting evidence distinguishable.',
            'audiences' => ['People resuming interrupted projects', 'Teams auditing decisions and drift', 'Applications needing evidence-backed explanations'],
            'inputs' => ['A question or briefing request', 'Retrieved historical evidence', 'Time, project, entity, and completeness constraints'],
            'workflow' => [
                ['name' => 'Frame question', 'description' => 'The caller defines the historical question and project scope.'],
                ['name' => 'Retrieve evidence', 'description' => 'Relevant records are gathered before interpretation.'],
                ['name' => 'Build assertions', 'description' => 'Facts remain distinct from inferences, hypotheses, and recommendations.'],
                ['name' => 'Return cited result', 'description' => 'The answer reports completeness and preserves evidence routes.'],
            ],
            'outputs' => ['Cited answers and summaries', 'Timelines and comparisons', 'Resume-work briefings', 'Labeled uncertainty and completeness'],
            'interactions' => ['Ask a history question', 'Inspect cited evidence', 'Generate a briefing', 'Compare plans with observed history'],
            'integrations' => ['Funes history', 'Menard context packs', 'Replaceable model providers', 'Burdgeon workspace'],
            'data_boundaries' => ['Kilgore owns disposable interpretations.', 'Funes owns historical evidence.', 'Menard owns retrieval preparation.', 'Source records remain unchanged.'],
            'limits' => ['The first end-to-end contract is still being defined.', 'Hosted recurring analysis is not available yet.', 'Answer quality is bounded by available evidence.'],
        ],
        $plans('KILGORE', 'kilgore',
            ['Laravel interpretation contracts', 'Local cited answers and typed assertions', 'Timelines, briefings, and completeness reporting'],
            ['Hosted model-backed interpretation', 'Recurring project briefings and drift monitoring', 'Managed model usage, retained results, and support'],
        ),
    ),
    'logres' => $product(
        'Logres',
        'Software-development orchestration that turns requests into executable tasks and verified results.',
        'Logres translates requests into tasks and prompts, dispatches them to isolated targets, streams feedback, and returns code, tests, and artifacts.',
        'is delivered as a framework-neutral package and local application.',
        'is planned as hosted execution on Laravel Cloud with managed Orb targets.',
        [
            'purpose' => 'Request software work, review the plan, follow execution, answer questions, and receive one consolidated result.',
            'audiences' => ['People submitting requests from desktop or mobile', 'Operators reviewing execution', 'Applications using the Logres API'],
            'inputs' => ['An authenticated entitled account', 'A software-development request', 'Authorized workspace context', 'Constraints and acceptance criteria'],
            'workflow' => [
                ['name' => 'ExecutionRequest', 'description' => 'Logres receives the desired outcome, context, and constraints.'],
                ['name' => 'Translated Tasks', 'description' => 'The request becomes bounded tasks with dependencies and completion criteria.'],
                ['name' => 'TaskPrompt', 'description' => 'Each task receives only its required instructions and context.'],
                ['name' => 'ExecutionTarget selection', 'description' => 'Logres selects an explicit target; the MVP uses an Orb.'],
                ['name' => 'Orb API dispatch', 'description' => 'The task and workspace policy are sent to the selected Orb.'],
                ['name' => 'Execution feedback', 'description' => 'Events, artifacts, failures, and questions return to Logres.'],
                ['name' => 'Caller response', 'description' => 'The caller answers decisions or missing-input requests.'],
                ['name' => 'Aggregated response', 'description' => 'Logres combines task outcomes into one final result.'],
            ],
            'outputs' => ['A traceable task plan', 'Live status and input requests', 'Code, tests, documents, screenshots, and artifacts', 'A final aggregated result'],
            'interactions' => ['Submit a request', 'Review tasks and targets', 'Follow events', 'Respond to input requests', 'Review results'],
            'integrations' => ['Codex', 'Claude', 'Amp', 'Grok', 'Orb', 'Additional contract-compatible agents and targets'],
            'data_boundaries' => ['Accounts owns identity and entitlements.', 'Logres owns requests, tasks, prompts, runs, and results.', 'Orb owns the execution environment.', 'Stripe owns subscription commerce.'],
            'limits' => ['Hosted execution is not available yet.', 'Orb is the MVP target.', 'Workspace authorization, duration, transport, and process launching require decisions.', 'NativePHP follows Laravel Cloud.'],
        ],
        $plans('LOGRES', 'logres',
            ['Framework-neutral execution contracts and kernel', 'Local request and task-planning workflow', 'Local development, tests, and result inspection'],
            ['Hosted request orchestration and managed Orb execution', 'Live feedback and caller-response workflow', 'Retained runs, artifacts, integrations, and support'],
        ),
    ),
    'menard' => $product(
        'Menard',
        'Citable, token-budgeted retrieval preparation for large archives.',
        'Menard turns heterogeneous collections into stable passages, replaceable indexes, ranked evidence, and compact cited context packs.',
        'is planned as a portable retrieval package.',
        'is planned as hosted indexing, semantic retrieval, and managed context assembly.',
        [
            'purpose' => 'Prepare the smallest useful body of evidence for a question without treating search projections as authoritative history.',
            'audiences' => ['Developers building retrieval systems', 'Teams with large archives', 'Applications assembling grounded model context'],
            'inputs' => ['Citable source records', 'Passage and indexing strategy', 'A retrieval query', 'An explicit token budget'],
            'workflow' => [
                ['name' => 'Create passages', 'description' => 'Source material becomes stable passages with structure-aware boundaries.'],
                ['name' => 'Build projection', 'description' => 'Keyword, vector, or hybrid indexes are replaceable derived data.'],
                ['name' => 'Retrieve and rerank', 'description' => 'Candidates are scored, deduplicated, expanded, and ordered.'],
                ['name' => 'Assemble context', 'description' => 'The strongest cited evidence is selected within the budget.'],
            ],
            'outputs' => ['Stable cited passages', 'Replaceable search indexes', 'Observable rankings', 'Token-budgeted context packs'],
            'interactions' => ['Index a collection', 'Submit a query', 'Inspect candidates', 'Build a context pack', 'Follow citations'],
            'integrations' => ['Funes evidence', 'Keyword and vector search providers', 'Kilgore interpretation', 'Burdgeon workspace'],
            'data_boundaries' => ['Sources and Funes remain authoritative.', 'Menard owns passages, indexes, retrieval, and context assembly.', 'Indexes are disposable.', 'Consumers interpret results.'],
            'limits' => ['The first retrieval milestone is still in development.', 'Hosted indexing is not available yet.', 'Quality depends on source coverage and configured providers.'],
        ],
        $plans('MENARD', 'menard',
            ['Portable passage and retrieval contracts', 'Local replaceable indexes and cited results', 'Deterministic token-budgeted context assembly'],
            ['Hosted indexing and semantic retrieval', 'Managed embeddings, reranking, and context assembly', 'Larger collections, retained indexes, monitoring, and support'],
        ),
    ),
];
