<?php

return [
    'documents' => [
        'privacy' => [
            'title' => 'Privacy Policy',
            'category' => 'Legal',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'terms' => [
            'title' => 'Terms of Service',
            'category' => 'Legal',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'acceptable-use' => [
            'title' => 'Acceptable Use Policy',
            'category' => 'Legal',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'refunds' => [
            'title' => 'Refund and Dispute Policy',
            'category' => 'Commerce',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'cancellations' => [
            'title' => 'Subscription Cancellation Policy',
            'category' => 'Commerce',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'delivery' => [
            'title' => 'Digital Service Delivery Policy',
            'category' => 'Commerce',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'cookies' => [
            'title' => 'Cookie Policy',
            'category' => 'Legal',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'data-processing' => [
            'title' => 'Data Processing Addendum',
            'category' => 'Legal',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'security' => [
            'title' => 'Security',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'subprocessors' => [
            'title' => 'Subprocessors',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'accessibility' => [
            'title' => 'Accessibility Statement',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'data-retention' => [
            'title' => 'Data Retention and Deletion',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'vulnerability-disclosure' => [
            'title' => 'Vulnerability Disclosure Policy',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
    ],
];
