<?php

return [
    'documents' => [
        'privacy' => [
            'title' => 'Privacy Policy',
            'category' => 'Legal',
            'version' => env('BUSINESS_POLICY_VERSION'),
            'effective_at' => env('BUSINESS_POLICY_EFFECTIVE_AT'),
            'published' => env('POLICY_PRIVACY_PUBLISHED', false),
            'content_path' => resource_path('policies/privacy.md'),
        ],
        'terms' => [
            'title' => 'Terms of Service',
            'category' => 'Legal',
            'version' => env('BUSINESS_POLICY_VERSION'),
            'effective_at' => env('BUSINESS_POLICY_EFFECTIVE_AT'),
            'published' => env('POLICY_TERMS_PUBLISHED', false),
            'content_path' => resource_path('policies/terms.md'),
        ],
        'acceptable-use' => [
            'title' => 'Acceptable Use Policy',
            'category' => 'Legal',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'refunds' => [
            'title' => 'Refund and Dispute Policy',
            'category' => 'Commerce',
            'version' => env('BUSINESS_POLICY_VERSION'),
            'effective_at' => env('BUSINESS_POLICY_EFFECTIVE_AT'),
            'published' => env('POLICY_REFUNDS_PUBLISHED', false),
            'content_path' => resource_path('policies/refunds.md'),
        ],
        'cancellations' => [
            'title' => 'Subscription Cancellation Policy',
            'category' => 'Commerce',
            'version' => env('BUSINESS_POLICY_VERSION'),
            'effective_at' => env('BUSINESS_POLICY_EFFECTIVE_AT'),
            'published' => env('POLICY_CANCELLATIONS_PUBLISHED', false),
            'content_path' => resource_path('policies/cancellations.md'),
        ],
        'delivery' => [
            'title' => 'Digital Service Delivery Policy',
            'category' => 'Commerce',
            'version' => env('BUSINESS_POLICY_VERSION'),
            'effective_at' => env('BUSINESS_POLICY_EFFECTIVE_AT'),
            'published' => env('POLICY_DELIVERY_PUBLISHED', false),
            'content_path' => resource_path('policies/delivery.md'),
        ],
        'cookies' => [
            'title' => 'Cookie Policy',
            'category' => 'Legal',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'data-processing' => [
            'title' => 'Data Processing Addendum',
            'category' => 'Legal',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'security' => [
            'title' => 'Security',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'subprocessors' => [
            'title' => 'Subprocessors',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'accessibility' => [
            'title' => 'Accessibility Statement',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'data-retention' => [
            'title' => 'Data Retention and Deletion',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
        'vulnerability-disclosure' => [
            'title' => 'Vulnerability Disclosure Policy',
            'category' => 'Compliance',
            'version' => null,
            'effective_at' => null,
            'published' => false,
            'content' => null,
        ],
    ],
];
